# Generated by Django 4.2 on 2023-07-13 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0014_alter_car_license_plate'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='top',
            field=models.BooleanField(default=False),
        ),
    ]
