# Generated by Django 4.2 on 2023-06-13 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='birhtday',
            field=models.DateTimeField(null=True, verbose_name='Дата рождения'),
        ),
        migrations.AddField(
            model_name='driver',
            name='license_category',
            field=models.CharField(max_length=10, null=True, verbose_name='Категория права'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='first_name',
            field=models.CharField(max_length=50, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='last_name',
            field=models.CharField(max_length=50, verbose_name='Фамилия'),
        ),
    ]
