# Generated by Django 4.2 on 2023-06-13 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0002_driver_birhtday_driver_license_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='driving_experience',
            field=models.CharField(max_length=20, null=True, verbose_name='Стаж вождения'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='address',
            field=models.CharField(max_length=256, null=True, verbose_name='Место проживания'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='avatar',
            field=models.ImageField(null=True, upload_to='drivers/avatars', verbose_name='Фотография водителя'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='birhtday',
            field=models.DateField(null=True, verbose_name='Дата рождения'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='phone',
            field=models.CharField(max_length=50, null=True, verbose_name='Номер водителя'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='position',
            field=models.CharField(choices=[('ADMIN', 'Администратор'), ('MANAGER', 'Менеджер'), ('DRIVER', 'Водитель')], max_length=20, null=True, verbose_name='Позиция пользователя'),
        ),
    ]
