# Generated by Django 4.2 on 2023-06-13 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0003_driver_driving_experience_alter_driver_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='birhtday',
            field=models.DateField(blank=True, null=True, verbose_name='Дата рождения'),
        ),
    ]
