# Generated by Django 4.2 on 2023-06-13 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0004_alter_driver_birhtday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='birhtday',
            field=models.DateField(null=True, verbose_name='Дата рождения'),
        ),
    ]
