# Generated by Django 4.2 on 2023-06-13 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0006_alter_driver_birhtday'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driver',
            name='birhtday',
        ),
        migrations.AddField(
            model_name='driver',
            name='birthday',
            field=models.DateField(null=True, verbose_name='Дата рождения'),
        ),
    ]
