# Generated by Django 4.2 on 2023-06-14 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0011_alter_driver_rented_car'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='cash_verified',
            field=models.BooleanField(default=False, verbose_name='Верификация оплаты'),
        ),
    ]
