# Generated by Django 4.2 on 2023-06-14 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0013_alter_driver_surname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='surname',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Отчество'),
        ),
    ]
