# Generated by Django 4.2 on 2023-06-15 17:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0010_car_image2_car_image3_car_image4_car_image5_and_more'),
        ('drivers', '0014_alter_driver_surname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='rented_car',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='cars.car', verbose_name='Арендованная машина'),
        ),
    ]
