# Generated by Django 4.2 on 2023-06-15 18:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0015_alter_driver_rented_car'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='rented_date',
            field=models.DateField(default=django.utils.timezone.now, null=True, verbose_name='Дата аренды'),
        ),
    ]
