# Generated by Django 4.2 on 2023-06-15 18:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0016_alter_driver_rented_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='cash_prove',
            field=models.ImageField(null=True, upload_to='', verbose_name='Фотография последнего чека'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='rented_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Дата аренды'),
        ),
    ]
