# Generated by Django 4.2 on 2023-07-13 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_user_uid'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='published_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Время регистрации пользователя'),
        ),
        migrations.AddField(
            model_name='user',
            name='rented_to',
            field=models.DateField(null=True, verbose_name='Дата аренды "до"'),
        ),
        migrations.AlterField(
            model_name='user',
            name='rented_date',
            field=models.DateField(null=True, verbose_name='Дата аренды "с"'),
        ),
    ]
